version: "3.9"
services:
  fravega-mysql-container:
    container_name: fravega-mysql-container
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fravega-locations-db
      - MYSQL_USER=bbisio
      - MYSQL_PASSWORD=password
    volumes:
      - "/data/mysql"
  fravega-locations-app-container:
    container_name: fravega-locations-app-container
    image: fravega-locations-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - fravega-mysql-container
    ports:
      - 8087:8080
    volumes:
      - "/data/spring-boot-app"